version: "3.9"

services:
  deno:
    container_name: deno
    image: deno
    build:
      context: .
      dockerfile: ./.docker/fresh/Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./src/fresh:/app
    command: sh -c "deno run --allow-net --allow-read --allow-write --allow-env --allow-run --watch=static/,routes/ main.ts"
